import assert from "node:assert/strict";
import test from "node:test";
import {
  extractReviewReceipt,
  REVIEW_ARCHIVE_LIMITS,
} from "../.github/scripts/merge-policy-artifact-zip.mjs";

// Independent fixtures: Python stdlib zipfile.ZipFile/writestr, stored and
// deflated, using BytesIO and a non-seekable BytesIO to obtain data descriptors.
// They are intentionally constants, not generated by the decoder under test.
const fixtureText = '{"complete":true,"findings":[]}';
const archives = {
  stored:
    "UEsDBBQAAAAAAABgK10OHtQXHwAAAB8AAAALAAAAcmV2aWV3Lmpzb257ImNvbXBsZXRlIjp0cnVlLCJmaW5kaW5ncyI6W119UEsBAhQDFAAAAAAAAGArXQ4e1BcfAAAAHwAAAAsAAAAAAAAAAAAAAKSBAAAAAHJldmlldy5qc29uUEsFBgAAAAABAAEAOQAAAEgAAAAAAA==",
  storedDescriptor:
    "UEsDBBQACAAAAABgK10AAAAAAAAAAAAAAAALAAAAcmV2aWV3Lmpzb257ImNvbXBsZXRlIjp0cnVlLCJmaW5kaW5ncyI6W119UEsHCA4e1BcfAAAAHwAAAFBLAQIUAxQACAAAAABgK10OHtQXHwAAAB8AAAALAAAAAAAAAAAAAACkgQAAAAByZXZpZXcuanNvblBLBQYAAAAAAQABADkAAABYAAAAAAA=",
  deflated:
    "UEsDBBQAAAAIAABgK10OHtQXIQAAAB8AAAALAAAAcmV2aWV3Lmpzb26rVkrOzy3ISS1JVbIqKSpN1VFKy8xLycxLL1ayio6tBQBQSwECFAMUAAAACAAAYCtdDh7UFyEAAAAfAAAACwAAAAAAAAAAAAAApIEAAAAAcmV2aWV3Lmpzb25QSwUGAAAAAAEAAQA5AAAASgAAAAAA",
  deflatedDescriptor:
    "UEsDBBQACAAIAABgK10AAAAAAAAAAAAAAAALAAAAcmV2aWV3Lmpzb26rVkrOzy3ISS1JVbIqKSpN1VFKy8xLycxLL1ayio6tBQBQSwcIDh7UFyEAAAAfAAAAUEsBAhQDFAAIAAgAAGArXQ4e1BchAAAAHwAAAAsAAAAAAAAAAAAAAKSBAAAAAHJldmlldy5qc29uUEsFBgAAAAABAAEAOQAAAFoAAAAAAA==",
  maximum:
    "UEsDBBQAAAAIAIZFK10LUUloTwAAAAAAAQALAAAAcmV2aWV3Lmpzb27twYEAAAAAgCCl/ekWqQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqUEsBAhQDFAAAAAgAhkUrXQtRSWhPAAAAAAABAAsAAAAAAAAAAAAAAIABAAAAAHJldmlldy5qc29uUEsFBgAAAAABAAEAOQAAAHgAAAAAAA==",
  oversized:
    "UEsDBBQAAAAIAIZFK134T2FjUAAAAAEAAQALAAAAcmV2aWV3Lmpzb27twYEAAAAAwyCl+dP9IFUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADADVBLAQIUAxQAAAAIAIZFK134T2FjUAAAAAEAAQALAAAAAAAAAAAAAACAAQAAAAByZXZpZXcuanNvblBLBQYAAAAAAQABADkAAAB5AAAAAAA=",
};
function fixture(which = "stored") {
  return Buffer.from(archives[which], "base64");
}
function offsets(bytes) {
  const end = bytes.length - 22;
  return { end, central: bytes.readUInt32LE(end + 16) };
}
function rejects(bytes, code) {
  assert.throws(
    () => extractReviewReceipt(bytes, "review.json"),
    (error) => {
      assert.equal(error.name, "ReviewArchiveError");
      assert.match(error.code, /^[a-z_]+$/);
      assert.equal(error.message, `Review archive: ${error.code}`);
      if (code) assert.equal(error.code, code);
      return true;
    },
  );
}

test("decodes independent stored/deflated and streamed ZIP fixtures", () => {
  for (const which of [
    "stored",
    "deflated",
    "storedDescriptor",
    "deflatedDescriptor",
  ]) {
    const bytes = fixture(which);
    const decoded = extractReviewReceipt(bytes, "review.json");
    assert.equal(decoded.toString(), fixtureText);
    decoded.fill(0);
    assert.equal(
      extractReviewReceipt(bytes, "review.json").toString(),
      fixtureText,
    );
  }
});

test("accepts plain Uint8Array views and returns a defensive Buffer", () => {
  const original = fixture();
  const backing = new Uint8Array(original.length + 8);
  backing.set(original, 4);
  const view = backing.subarray(4, 4 + original.length);
  const result = extractReviewReceipt(view, "review.json");
  assert.ok(Buffer.isBuffer(result));
  backing.fill(0);
  assert.equal(result.toString(), fixtureText);
});

test("accepts supported UTF8 flags, DOS creator and Unix archive attributes", () => {
  for (const platform of [0, 3]) {
    const bytes = fixture("storedDescriptor");
    const { central } = offsets(bytes);
    bytes[central + 5] = platform;
    bytes.writeUInt16LE(0x0808, 6);
    bytes.writeUInt16LE(0x0808, central + 8);
    bytes.writeUInt32LE(platform === 0 ? 0x20 : 0x81a40020, central + 38);
    assert.equal(
      extractReviewReceipt(bytes, "review.json").toString(),
      fixtureText,
    );
  }
});

test("rejects hostile byte objects without invoking getters or iterators", () => {
  let called = 0;
  const hostile = () => {
    called++;
    throw new Error("private payload");
  };
  for (const property of [
    "byteLength",
    "buffer",
    "byteOffset",
    Symbol.iterator,
  ]) {
    const bytes = fixture();
    Object.defineProperty(bytes, property, { get: hostile });
    rejects(bytes, "invalid_bytes");
  }
  const fake = Object.create(Uint8Array.prototype);
  Object.defineProperty(fake, "byteLength", { get: hostile });
  rejects(fake, "invalid_bytes");
  rejects(
    new Proxy(fixture(), { get: hostile, getPrototypeOf: hostile }),
    "invalid_bytes",
  );
  class CustomBytes extends Uint8Array {}
  rejects(new CustomBytes(fixture()), "invalid_bytes");
  for (const OtherBytes of [Int8Array, Uint8ClampedArray]) {
    const disguised = new OtherBytes(fixture());
    Object.setPrototypeOf(disguised, Uint8Array.prototype);
    rejects(disguised, "invalid_bytes");
  }
  rejects(new DataView(fixture().buffer), "invalid_bytes");
  rejects(
    new Uint8Array(new SharedArrayBuffer(fixture().length)),
    "invalid_bytes",
  );
  rejects({ [Symbol.iterator]: hostile }, "invalid_bytes");
  assert.equal(called, 0);
});

test("enforces frozen archive and decompressed receipt limits", () => {
  assert.ok(Object.isFrozen(REVIEW_ARCHIVE_LIMITS));
  assert.deepEqual(REVIEW_ARCHIVE_LIMITS, {
    archiveBytes: 262144,
    receiptBytes: 65536,
  });
  rejects(
    Buffer.alloc(REVIEW_ARCHIVE_LIMITS.archiveBytes + 1),
    "archive_limit",
  );
  const maximum = extractReviewReceipt(fixture("maximum"), "review.json");
  assert.equal(maximum.length, 65536);
  assert.ok(maximum.every((byte) => byte === 48));
  rejects(fixture("oversized"), "receipt_limit");
  const lying = fixture("oversized");
  const { central } = offsets(lying);
  lying.writeUInt32LE(1, 22);
  lying.writeUInt32LE(1, central + 24);
  rejects(lying, "invalid_compressed_data");
});

test("rejects wrong expected names and unsafe paths without reflecting names", () => {
  for (const name of [
    "../bad.json",
    "/review.json",
    "a/review.json",
    "a\\review.json",
    "review.json\0",
    "review.JSON",
    "x".repeat(200) + ".json",
    {
      toString() {
        throw new Error("secret");
      },
    },
  ]) {
    assert.throws(() => extractReviewReceipt(fixture(), name), {
      code: "invalid_expected_name",
    });
  }
  assert.throws(() => extractReviewReceipt(fixture(), "another.json"), {
    name: "ReviewArchiveError",
  });
  for (const name of [
    "../bad.json",
    "/bad__.json",
    "a\\view.json",
    "a/view.json",
  ]) {
    const bytes = fixture();
    const { central } = offsets(bytes);
    assert.equal(Buffer.byteLength(name), 11);
    bytes.write(name, 30, "ascii");
    bytes.write(name, central + 46, "ascii");
    rejects(bytes, "name_mismatch");
  }
});

test("rejects truncation, prefixes, suffixes and false end records", () => {
  for (const which of ["stored", "deflatedDescriptor"]) {
    const bytes = fixture(which);
    for (let length = 0; length < bytes.length; length++)
      rejects(bytes.subarray(0, length));
    rejects(Buffer.concat([Buffer.from([0]), bytes]));
    rejects(Buffer.concat([bytes, Buffer.from([0])]));
    rejects(Buffer.concat([bytes, bytes.subarray(-22)]));
  }
});

test("rejects extra/duplicate entries, split disks, comments and wrong offsets", () => {
  const mutators = [
    (b, c, e) => b.writeUInt16LE(2, e + 8),
    (b, c, e) => b.writeUInt16LE(2, e + 10),
    (b, c, e) => b.writeUInt16LE(1, e + 4),
    (b, c, e) => b.writeUInt16LE(1, e + 6),
    (b, c, e) => b.writeUInt16LE(1, e + 20),
    (b, c) => b.writeUInt16LE(1, c + 32),
    (b, c) => b.writeUInt16LE(1, c + 34),
    (b, c) => b.writeUInt32LE(1, c + 42),
    (b, c, e) => b.writeUInt32LE(0xffffffff, e + 16),
    (b, c, e) => b.writeUInt32LE(0xffffffff, e + 12),
  ];
  for (const mutate of mutators) {
    const bytes = fixture();
    const { central, end } = offsets(bytes);
    mutate(bytes, central, end);
    rejects(bytes);
  }
  const bytes = fixture();
  const { central, end } = offsets(bytes);
  const extraCentral = Buffer.concat([
    bytes.subarray(0, end),
    bytes.subarray(central, end),
    bytes.subarray(end),
  ]);
  extraCentral.writeUInt32LE((end - central) * 2, extraCentral.length - 10);
  rejects(extraCentral);
});

test("rejects directory, symlink, special file and unsupported ZIP features", () => {
  for (const mode of [0o040755, 0o120777, 0o060600, 0o010600]) {
    const bytes = fixture();
    bytes.writeUInt32LE((mode << 16) >>> 0, offsets(bytes).central + 38);
    rejects(bytes, "nonregular_entry");
  }
  const directory = fixture();
  directory.writeUInt32LE(0x10, offsets(directory).central + 38);
  rejects(directory, "nonregular_entry");
  for (const flags of [1, 0x40, 0x2000, 0x8000]) {
    const bytes = fixture();
    bytes.writeUInt16LE(flags, 6);
    bytes.writeUInt16LE(flags, offsets(bytes).central + 8);
    rejects(bytes, "unsupported_format");
  }
  for (const method of [9, 12, 99]) {
    const bytes = fixture();
    bytes.writeUInt16LE(method, 8);
    bytes.writeUInt16LE(method, offsets(bytes).central + 10);
    rejects(bytes, "unsupported_format");
  }
  const zip64 = fixture();
  zip64.writeUInt16LE(45, 4);
  zip64.writeUInt16LE(45, offsets(zip64).central + 6);
  rejects(zip64, "unsupported_format");
});

test("checks CRC, stored length and every local/central declaration", () => {
  const corrupt = fixture();
  corrupt[41] ^= 1;
  rejects(corrupt, "checksum_mismatch");
  for (const offset of [4, 6, 8, 10, 14, 18, 22, 26, 28, 30]) {
    const bytes = fixture();
    bytes[offset] ^= 1;
    rejects(bytes);
  }
  const wrongSize = fixture();
  wrongSize.writeUInt32LE(30, 22);
  wrongSize.writeUInt32LE(30, offsets(wrongSize).central + 24);
  rejects(wrongSize);
  const wrongCrc = fixture();
  wrongCrc.writeUInt32LE(0, 14);
  wrongCrc.writeUInt32LE(0, offsets(wrongCrc).central + 16);
  rejects(wrongCrc, "checksum_mismatch");
});

test("accepts signed/unsigned descriptors and rejects mismatched descriptors", () => {
  for (const which of ["storedDescriptor", "deflatedDescriptor"]) {
    const bytes = fixture(which);
    const { central } = offsets(bytes);
    const unsigned = Buffer.concat([
      bytes.subarray(0, central - 16),
      bytes.subarray(central - 12),
    ]);
    unsigned.writeUInt32LE(central - 4, unsigned.length - 6);
    assert.equal(
      extractReviewReceipt(unsigned, "review.json").toString(),
      fixtureText,
    );
    for (const position of [
      central - 16,
      central - 12,
      central - 8,
      central - 4,
    ]) {
      const corrupt = Buffer.from(bytes);
      corrupt[position] ^= 1;
      rejects(corrupt);
    }
    const partialLocal = Buffer.from(bytes);
    partialLocal.writeUInt32LE(31, 22);
    rejects(partialLocal);
  }
});

test("rejects compressed trailing data and forged uncompressed sizes", () => {
  const bytes = fixture("deflated");
  const { central } = offsets(bytes);
  const extra = Buffer.concat([
    bytes.subarray(0, central),
    Buffer.from([0]),
    bytes.subarray(central),
  ]);
  extra.writeUInt32LE(34, 18);
  extra.writeUInt32LE(34, central + 1 + 20);
  extra.writeUInt32LE(central + 1, extra.length - 6);
  rejects(extra, "invalid_compressed_data");
  const wrongSize = fixture("deflated");
  wrongSize.writeUInt32LE(30, 22);
  wrongSize.writeUInt32LE(30, central + 24);
  rejects(wrongSize, "size_mismatch");
});

test("rejects malformed, ZIP64 and alternate-path extra fields", () => {
  const original = fixture();
  const { central } = offsets(original);
  for (const extra of [
    Buffer.from([1]),
    Buffer.from([1, 0, 0, 0]),
    Buffer.from([0x75, 0x70, 0, 0]),
    Buffer.from([0x55, 0x54, 8, 0, 1]),
  ]) {
    const bytes = Buffer.concat([
      original.subarray(0, 41),
      extra,
      original.subarray(41),
    ]);
    bytes.writeUInt16LE(extra.length, 28);
    bytes.writeUInt32LE(central + extra.length, bytes.length - 6);
    rejects(bytes);
  }
});

test("accepts a standard mtime extra and rejects duplicate timestamps", () => {
  const original = fixture();
  const { central } = offsets(original);
  const timestamp = Buffer.from([0x55, 0x54, 5, 0, 1, 0, 0, 0, 0]);
  for (const count of [1, 2]) {
    const extra = Buffer.concat(Array(count).fill(timestamp));
    const bytes = Buffer.concat([
      original.subarray(0, 41),
      extra,
      original.subarray(41),
    ]);
    bytes.writeUInt16LE(extra.length, 28);
    bytes.writeUInt32LE(central + extra.length, bytes.length - 6);
    if (count === 1)
      assert.equal(
        extractReviewReceipt(bytes, "review.json").toString(),
        fixtureText,
      );
    else rejects(bytes, "unsupported_extra");
  }
});
